import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateFeeReceipt = (feeData, schoolName = "Iqbal High School Kot Abdullah") => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(41, 128, 185); // Blue color
  doc.text(schoolName, 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Fee Payment Receipt", 105, 30, { align: 'center' });
  
  // Receipt Info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const dateStr = format(new Date(), 'dd MMM yyyy HH:mm');
  doc.text(`Date: ${dateStr}`, 14, 40);
  doc.text(`Receipt No: ${feeData.receiptNo || Math.floor(Math.random() * 1000000)}`, 150, 40);
  
  // Student Details Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(245, 247, 250);
  doc.rect(14, 45, 182, 35, 'F');
  doc.rect(14, 45, 182, 35, 'S');
  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Student Name: ${feeData.studentName}`, 20, 55);
  doc.text(`Father's Name: ${feeData.fatherName || 'N/A'}`, 110, 55);
  doc.text(`Class: ${feeData.classId}`, 20, 65);
  doc.text(`Roll No: ${feeData.rollNo || 'N/A'}`, 110, 65);
  doc.text(`Month/Year: ${feeData.month} ${feeData.year}`, 20, 75);
  
  // Payment Details Table
  const tableColumn = ["Description", "Amount (PKR)"];
  const tableRows = [
    ["Total Monthly Fee", `${feeData.total}`],
    ["Amount Paid", `${feeData.paid}`],
    ["Balance / Due", `${feeData.due}`],
    ["Status", `${feeData.status ? feeData.status.toUpperCase() : 'N/A'}`]
  ];
  
  autoTable(doc, {
    startY: 90,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185], textColor: 255 },
    styles: { fontSize: 12, cellPadding: 3 },
  });
  
  // Footer
  const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : 130;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("This is a computer-generated receipt and does not require a signature.", 105, finalY + 20, { align: 'center' });
  
  doc.setFontSize(8);
  doc.text("Generated by SMS System", 105, finalY + 25, { align: 'center' });
  
  // Save PDF
  doc.save(`Receipt_${feeData.studentName}_${feeData.month}_${feeData.year}.pdf`);
};

export const generateExpenseReceipt = (expenseData, schoolName = "Iqbal High School Kot Abdullah") => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(192, 57, 43); // Red color for expense
  doc.text(schoolName, 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Expense Voucher", 105, 30, { align: 'center' });
  
  // Receipt Info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const dateStr = format(new Date(), 'dd MMM yyyy HH:mm');
  doc.text(`Date: ${dateStr}`, 14, 40);
  doc.text(`Voucher No: ${expenseData.id ? expenseData.id.slice(0, 8).toUpperCase() : Math.floor(Math.random() * 1000000)}`, 150, 40);
  
  // Expense Details Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(253, 237, 236); // Light red background
  doc.rect(14, 45, 182, 25, 'F');
  doc.rect(14, 45, 182, 25, 'S');
  
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Description: ${expenseData.description}`, 20, 55);
  doc.text(`Category: ${expenseData.category}`, 20, 63);
  doc.text(`Expense Date: ${expenseData.date}`, 120, 55);
  
  // Amount Details Table
  const tableColumn = ["Description", "Amount (PKR)"];
  const tableRows = [
    [expenseData.description, `${expenseData.amount}`],
    ["Category", expenseData.category],
    ["Total Amount", `${expenseData.amount}`]
  ];
  
  autoTable(doc, {
    startY: 80,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [192, 57, 43], textColor: 255 }, // Red header
    styles: { fontSize: 12, cellPadding: 3 },
  });
  
  // Footer
  const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY : 120;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  
  // Signature Lines
  doc.setDrawColor(150, 150, 150);
  doc.line(20, finalY + 40, 70, finalY + 40);
  doc.text("Authorized Signature", 25, finalY + 45);
  
  doc.line(140, finalY + 40, 190, finalY + 40);
  doc.text("Receiver Signature", 145, finalY + 45);
  
  doc.text("This is a computer-generated voucher.", 105, finalY + 65, { align: 'center' });
  doc.setFontSize(8);
  doc.text("Generated by SMS System", 105, finalY + 70, { align: 'center' });
  
  // Save PDF
  doc.save(`Expense_${expenseData.date}_${expenseData.category}.pdf`);
};

export const exportResultsToExcel = (data, fileName = "Results_Report") => {
    // This will be implemented later, placing placeholder here if needed or separate file
};
